# Generated by Django 6.0.2 on 2026-02-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profilepictures/user-default.png', null=True, upload_to='profilepictures'),
        ),
    ]
