# Generated by Django 6.0.2 on 2026-02-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profilepictures/userdefault.png', null=True, upload_to='profilepictures'),
        ),
    ]
