# Generated by Django 6.0.2 on 2026-02-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_website',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
