# Generated by Django 6.0.2 on 2026-02-04 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfordevelopers', '0002_tag_project_vote_ratio_project_vote_total_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='appfordevelopers.profile'),
        ),
    ]
