# Generated by Django 6.0.2 on 2026-02-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfordevelopers', '0005_project_demo_link_project_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='appfordevelopers.profile'),
            preserve_default=False,
        ),
    ]
