# Generated by Django 6.0.2 on 2026-02-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfordevelopers', '0007_alter_project_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='static/images/featured-images'),
        ),
    ]
