# Generated by Django 6.0.2 on 2026-02-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfordevelopers', '0008_project_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='featured-images/default.jpg', null=True, upload_to='featured-images'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
