# Generated by Django 6.0.2 on 2026-02-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfordevelopers', '0011_alter_project_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
