# Generated by Django 6.0.2 on 2026-02-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfordevelopers', '0012_alter_review_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', '-created', 'title']},
        ),
    ]
