# Generated by Django 6.0.2 on 2026-02-23 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfordevelopers', '0013_alter_project_options'),
        ('users', '0007_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.profile'),
        ),
    ]
